### ISSUE TITLE
Reading bumped version in config

### ISSUE THREAD

**Issue by MMRandy** [Ragnarokkr/grunt-bumpx#2]
Cool plugin, thanks for sharing.  However, I have an interesting dilema when it comes to reading the bumped version into another task in the config.  Was wondering if you've handled this another way or what.  Say I have the following in my gruntfile:

```
bump: {
    options: {
        part: 'patch'
    },
    files: ['package.json']
},
pkg: grunt.file.readJSON('package.json'),
```

Then say I want to display the new version in the footer of the main page.  I am firing a string-replace task after the version bump task that does something like this:

```
...
}, {
    pattern: /@@appVersion/ig,
    replacement: '<%= pkg.version %>'
}]
...
```

The problem is that the package.json will be read before the bump task is able to bump the version, for obvious reasons, which means the version I show will never match the one that is currently residing in the package.json.  Aside from duplicating the functionality of bumpx and placing it into a pure JS function that fires before the config is initialized, can you think of any other way to accomplish what I am trying to do?  

If I augment the bumpx code like so:

```
if (newVer) {
    f.version = newVer;
    grunt.file.write(filepath, JSON.stringify(f, null, 2));
    grunt.log.writeln(oldVer + ' -> ' + newVer);
    grunt.config.set('version', newVer);  // <==== new line
} // if
```

Then it works if I reference like so:

```
...
}, {
    pattern: /@@appVersion/ig,
    replacement: '<%= version %>'
}]
...
```

However, this feels a little hacky.  Any ideas on this?

Thx!

**Comment by Ragnarokkr** [comment]
Hi @MMRandy thanks for the feedback.

This plug-in was designed to be mainly called via CLI or in a task for itself, because when developed, I thought that this task would been useful only to bump the version just before to do a commit.

I never thought at the possibility to use the bump task together other tasks.

Your it's a good question. Since I have to update the plugin to support the new released version of grunt. I'll take a look to the code to figure out a valid way to solve this issue.

**Comment by MMRandy** [comment]
Thanks @Ragnarokkr!  Lemme know what you end up with...the workaround I mentioned above is working for me for now though :)

**Comment by Ragnarokkr** [comment]
@MMRandy Look if my last changes can be the answer to your question :)
