### ISSUE TITLE
Recursive error

### ISSUE THREAD

**Issue by evolutionxbox** [Ragnarokkr/grunt-bumpx#5]
Using: 

```
grunt --verbose
```

I get a result of:

```
(node) warning: Recursive process.nextTick detected. This will break in the next version of node. Please use setImmediate for recursive deferral.

util.js:35
  var str = String(f).replace(formatRegExp, function(x) {
                      ^
RangeError: Maximum call stack size exceeded
```

Using this Gruntfile.js:

``` javascript
module.exports = function(grunt) {

  // initialise le config
  grunt.initConfig({
    pkg: require('./package.json'),

    dir: {
      assets: 'assets',
      src: 'src'
    },

    bumpx: {
      options: {
        level: 'minor',
        src: ['package.json']
      }
    }
  });

  // load per task config from separate files
  grunt.loadNpmTasks('grunt-bumpx');

  // register alias tasks
  grunt.registerTask('bumpx', 'Bump that version!', ['bumpx']);
  grunt.registerTask('default', ['bumpx']);
};
```

and using this package.json

``` json
{
  "name": "project.name",
  "version": "0.0.1",
  "author": "Jonathan Cousins",
  "contributors": [],
  "homepage": "",
  "description": "",
  "repository": {
    ...
  },
  "devDependencies": {
    "grunt": "^0.4.4",
    "grunt-bumpx": "^0.2.0"
  }
}
```

**Comment by Ragnarokkr** [comment]
Hi, thanks for the report.

The problem is that you defined the `bumpx` property which doesn't exists as task, and this generates a recursive stack of calls inside Grunt, generating your exception.

The property **must be** `bump` instead of `bumpx`. (The name has been choosen to avoid a collision with an already existing plugin with the same name). Also, the registration of a task named `bumpx` is redundant in this case, since you can just call `grunt bump` on the CLI, without the need of a new task.

Finally, if you really need to change the name of the task, you can always use the Grunt's  `renameTask()` method.

**Comment by evolutionxbox** [comment]
Really well explained, thank you.

**Comment by Ragnarokkr** [comment]
You're welcome, and thanks to you for the time you've spent in testing and reporting. Have a nice day.
